In [2]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
import pandas as pd

import pydot 
from sklearn.externals.six import StringIO  
from IPython.display import Image 


data = pd.read_csv('titanic.csv')
data.head()


Couldn't import dot_parser, loading of dot files will not be possible.


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
filtered_data = data[['Pclass', 'Fare', 'Age', 'Sex']]
filtered_data = filtered_data.replace(['male', 'female'], [0, 1])
print filtered_data.count()
filtered_data.head()

Pclass    891
Fare      891
Age       714
Sex       891
dtype: int64


Pclass     Fare  Age  Sex
0       3   7.2500   22    0
1       1  71.2833   38    1
2       3   7.9250   26    1
3       1  53.1000   35    1
4       3   8.0500   35    0

In [4]:
samples = filtered_data[np.isfinite(filtered_data['Age'])]
print samples.count()

Pclass    714
Fare      714
Age       714
Sex       714
dtype: int64


In [5]:
features = data[np.isfinite(filtered_data['Age'])]['Survived']
print features.count()
features.head()

714


0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [6]:
clf = DecisionTreeClassifier(random_state=10)
clf.fit(samples, features)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=10, splitter='best')

In [7]:
importances = clf.feature_importances_
importances

array([ 0.13800177,  0.31502327,  0.24646275,  0.30051221])

In [8]:
f = open('answers/2.1', 'w')
f.write('Fare Sex')
f.close()

In [9]:
clf.predict([[1, 1.1000, 60, 0]])

array([0])

In [10]:
clf.predict([[1, 100.1000, 30, 1]])

array([1])

In [12]:
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
#graph.write_pdf('tree.pdf')
#Image(graph.create_png()) 

NameError: global name 'dot_parser' is not defined