In [64]:
import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.preprocessing import scale
from sklearn.neighbors import KNeighborsRegressor
from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import KFold


In [65]:
data_set = datasets.load_boston()
print data_set.data.size
data_set.data[:2]


6578


array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00,
          0.00000000e+00,   5.38000000e-01,   6.57500000e+00,
          6.52000000e+01,   4.09000000e+00,   1.00000000e+00,
          2.96000000e+02,   1.53000000e+01,   3.96900000e+02,
          4.98000000e+00],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00,
          0.00000000e+00,   4.69000000e-01,   6.42100000e+00,
          7.89000000e+01,   4.96710000e+00,   2.00000000e+00,
          2.42000000e+02,   1.78000000e+01,   3.96900000e+02,
          9.14000000e+00]])

In [66]:
target = scale(data_set.target)
target[:2]

array([ 0.15968566, -0.10152429])

In [67]:
data = scale(data_set.data)
data[:2]

array([[-0.41771335,  0.28482986, -1.2879095 , -0.27259857, -0.14421743,
         0.41367189, -0.12001342,  0.1402136 , -0.98284286, -0.66660821,
        -1.45900038,  0.44105193, -1.0755623 ],
       [-0.41526932, -0.48772236, -0.59338101, -0.27259857, -0.74026221,
         0.19427445,  0.36716642,  0.55715988, -0.8678825 , -0.98732948,
        -0.30309415,  0.44105193, -0.49243937]])

In [68]:
maximum = -10000
p_res = 0

for p in np.linspace(1,10,num = 200):
    clr = KNeighborsRegressor(n_neighbors=5, weights='distance', metric='minkowski', p = p)
    kfold = KFold(500, n_folds=5 , random_state=42)
    
    res_iter =  cross_val_score(clr, data, y = target, scoring='mean_squared_error', cv=kfold).mean()
    #print '%.2f: %.2f' % (p, res_iter)
    if res_iter > maximum:
        maximum = res_iter
        p_res = p
        
#np.max(result[:, 1:1], axes = 0)
print 'p = %.1f' % abs(p_res)
print '%.1f' % maximum

f = open('answers/1.2', 'w')
#f.write('%.1f' % maximum)
f.write('%.1f' % abs(p_res))
f.close()



p = 1.4
-0.3
